'\" t
.\"
.\" Author: John Ogness
.\"
.\" This file has been put into the public domain.
.\" You can do whatever you want with this file.
.\"
.TH MCD_DUMP_DATA_DBUS_STOP 3 "2015-11-30" "Ericsson" "minicoredumper"
.
.SH NAME
mcd_dump_data_dbus_stop \- stop thread for D-Bus communication or inotify
fallback notification
.
.SH SYNOPSIS
.B #include <minicoredumper.h>
.PP
.B void mcd_dump_data_dbus_stop(void);
.PP
Compile and link with
.IR -lminicoredumper .
.
.SH DESCRIPTION
If D-Bus support is enabled,
.BR mcd_dump_data_dbus_stop ()
unregisters the application with
.BR minicoredumper_dbusd (1)
and shuts down the D-Bus connection. Otherwise, if the environment variable
MINICOREDUMPER_MONITOR exists and specifies an absolute path to a file,
the
.BR inotify (7)
instance is freed. In both cases
.BR mcd_dump_data_dbus_stop ()
waits for the thread created by
.BR mcd_dump_data_dbus_start (3)
to exit.
.
.SH "SEE ALSO"
.BR libminicoredumper (7),
.BR minicoredumper_dbusd (1),
.BR mcd_dump_data_dbus_start (3)
.PP
The DiaMon Workgroup: <http://www.diamon.org>
