'\" t
.\"
.\" Author: John Ogness
.\"
.\" This file has been put into the public domain.
.\" You can do whatever you want with this file.
.\"
.TH MINICOREDUMPER_REGD 1 "2016-09-07" "Ericsson" "minicoredumper"
.
.SH NAME
minicoredumper_regd \- a service to facilitate registration of
applications using
.BR libminicoredumper (7).
.
.SH SYNOPSIS
.B minicoredumper_regd
.
.SH DESCRIPTION
.B minicoredumper_regd
is responsible for managing the list of applications registered with
.BR libminicoredumper (7).
This list is used by the
.B minicoredumper (1)
to dump data registered by the various applications.
.B minicoredumper_regd
must be running before any applications using
.BR libminicoredumper (7)
are started.
.
.SH "SEE ALSO"
.BR minicoredumper (1),
.BR libminicoredumper (7),
.BR minicoredumper_trigger (1),
.BR minicoredumper.cfg.json (5),
.PP
The DiaMon Workgroup: <http://www.diamon.org>
