'\" t
.\"
.\" Copyright (c) 2015-2017 Linutronix GmbH
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright notice,
.\"    this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright notice,
.\"    this list of conditions and the following disclaimer in the documentation
.\"    and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.TH LIBMINICOREDUMPER 7 "2017-01-19" "minicoredumper" "minicoredumper"
.
.SH NAME
libminicoredumper \- a library for registering application data for dumping
with the
.BR minicoredumper (1)
.
.SH DESCRIPTION
.B libminicoredumper
provides an interface for registering binary and text data for dumping with
the
.BR minicoredumper (1).
The data can be dumped into a
.BR core (5)
file (in case this application crashes), or into separate files for simple
access.
.PP
If any data is registered for dumping, an anonymous UNIX domain socket is
used to send a message to
.BR minicoredumper_regd (1),
thus registering this application with the
.BR minicoredumper (1).
When some other application crashes, the
.BR minicoredumper (1)
will dump the registered data from this application as well. This feature
allows variable information from multiple applications to be dumped soon
after any application crashes. To minimize the time between an application
crash and the dumping of other registered applications, the
.BR minicoredumper (1)
uses PTRACE_SEIZE and PTRACE_INTERRUPT to temporarily pause registered
applications until all dumping is complete.
.
.SH "SEE ALSO"
.BR mcd_dump_data_register_bin (3),
.BR mcd_dump_data_register_text (3),
.BR mcd_dump_data_unregister (3),
.BR minicoredumper (1),
.BR minicoredumper.cfg.json (5),
.BR minicoredumper.recept.json (5),
.BR minicoredumper_regd (1),
.BR minicoredumper_trigger (1),
.BR coreinject (1)
.BR ptrace (2)
.PP
The DiaMon Workgroup: <http://www.diamon.org>
