'\" t
.\"
.\" Author: John Ogness
.\"
.\" This file has been put into the public domain.
.\" You can do whatever you want with this file.
.\"
.TH LIBMINICOREDUMPER 7 "2015-08-13" "Ericsson" "minicoredumper"
.
.SH NAME
libminicoredumper \- a library for registering application data for dumping
with the
.BR minicoredumper (1)
.
.SH DESCRIPTION
.B libminicoredumper
provides an interface for registering binary and text data for dumping with
the
.BR minicoredumper (1).
The data can be dumped into a
.BR core (5)
file (in case this application crashes), or into separate files for simple
access.
.PP
If activated in the library and enabled in the application,
.B libminicoredumper
is able to register with
.BR minicoredumper_dbusd (1)
via D-Bus. With this, when some other application crashes, this application
will be notified and also dump its registered variables. This allows variable
information from multiple applications to be dumped if any of the
applications crash.
.
.SH NOTES
In order for the
.BR minicoredumper (1)
to identify the registered data, the symbols
.I mcd_dump_data_head
and
.I mcd_dump_data_version
must not be stripped from
.BR libminicoredumper .
.
.SH "SEE ALSO"
.BR mcd_dump_data_register_bin (3),
.BR mcd_dump_data_register_text (3),
.BR mcd_dump_data_unregister (3),
.BR mcd_dump_data_dbus_start (3),
.BR mcd_dump_data_dbus_stop (3),
.BR minicoredumper (1),
.BR minicoredumper.cfg.json (5),
.BR minicoredumper.recept.json (5),
.BR minicoredumper_dbusd (1),
.BR minicoredumper_trigger (1),
.BR coreinject (1)
.PP
The DiaMon Workgroup: <http://www.diamon.org>
